Ldpc v2
quantumgizmos/ldpc pull request #18
Opened 2023-11-17 09:14 UTC by quantumgizmos

Complete rewrite. Should be backwards compatible with LDPCv1. Please test this on old scripts.

2023-11-26 15:27 UTC, lucasberent approved these changes
Checked the most important parts hopefully and added a few comments. I guess more hands on testing would be valuable.

2023-11-26 15:27 UTC, lucasberent commented on cpp_example/main.cpp
> +#include <iostream>
is this file needed?

2023-11-26 15:27 UTC, lucasberent commented on cpp_test/TestFlipDecoder.cpp
> +    for(int i = 2; i<8; i++){
I believe for indexing `std::size_t` is best to use as loop variable type

2023-11-26 15:27 UTC, lucasberent commented on cpp_test/TestFlipDecoder.cpp
> +        cout<<"Error: ";
should we leave in all cout statements in the release?

2023-11-26 15:27 UTC, lucasberent commented on cpp_test/TestGf2Dense.cpp
> +// TEST(gf2dense, hamming_code){
what about all this outcommented code?

2023-11-26 15:27 UTC, lucasberent commented on cpp_test/TestGf2Linalg.cpp
> +double sparsity = 0.01;
unsure if blobal variables adhere to the best practices here.

2023-11-26 15:27 UTC, lucasberent commented on cpp_test/TestSoftInfo.cpp
> +
lots of code commented out here

2023-11-26 15:27 UTC, lucasberent commented on cpp_test/TestUnionFind.cpp
> +
commented out code

2023-11-26 15:27 UTC, lucasberent commented on cpp_test/test_inputs/generate_tests.py
> +if __name__ == "__main__":
is a main function needed here?

2023-11-26 15:27 UTC, lucasberent commented on python_test/test_bp_decoder.py
> +if __name__ == "__main__":
needed?

2023-11-26 15:27 UTC, lucasberent commented on python_test/test_code_util.py
> +        H = hamming_code(i)
I guess using pytest.fixture would be the best practice to generate test objects used (also those used across different tests)

2024-01-11 12:21 UTC, lucasberent requested changes
some minor comments and potential improvements on the sinter integration.

2024-01-19 10:42 UTC, peter-janderks commented on src_python/ldpc/sinter_decoders/sinter_bposd_decoder.py
> +        self.bposd = BpOsdDecoder(self.matrices.check_matrix,
If I don't make a separate sinter_[decoder_name]_ for every decoder, then someone using Sinter in python can't see the the parameters the sinter_[decoder_name]_ excepts in their editor.  Do you know what I mean? For a Sinter user (who I'm targeting) I think this solution is the cleanest.

2024-01-19 10:46 UTC, peter-janderks commented on src_python/ldpc/sinter_decoders/sinter_bposd_decoder.py
>      def decode(self, syndrome: np.ndarray) -> np.ndarray:
Yes agreed, I made an example in [sinter_example.py](https://github.com/quantumgizmos/ldpc/blob/ldpc_v2/examples/sinter_example.py). Can you let me know what you think? To be clear, I don't want to write code that replaces Sinter and Stim, I simply want to use the BPOSD and BeliefFind as a plugin. Sinter and Stim have a full simulator that only takes a code and a decoder/-name.

2024-01-19 10:50 UTC, peter-janderks commented on src_python/ldpc/sinter_decoders/sinter_bposd_decoder.py
> +from beliefmatching import detector_error_model_to_check_matrices
I don't want to copy Oscar's code from beliefmatching. So I'll leave it as it is now. (Sidenote- if we want to optimize performance I don't think we should not convert detector error models to matrices).

2024-01-19 10:50 UTC, peter-janderks commented on src_python/ldpc/sinter_decoders/sinter_bposd_decoder.py
>          self,
Fixed now. The tmp_dir parameter is not optional

2024-01-19 11:53 UTC, peter-janderks commented
@lucasberent Thanks for the quick review 😃 . There are two comments left which I didn't resolve yet but I did comment on.

2024-01-22 14:55 UTC, lucasberent commented on src_python/ldpc/sinter_decoders/sinter_bposd_decoder.py
> +        self.bposd = BpOsdDecoder(self.matrices.check_matrix,
If you used named arguments that should work, no?

2024-01-22 14:56 UTC, lucasberent commented
> @lucasberent Thanks for the quick review 😃 . There are two comments left which I didn't resolve yet but I did comment on.

haven't tried it out myself yet but looks good! thanks

2024-10-23 13:48 UTC, merged